# Generated by Django 6.0.1 on 2026-07-06 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user'], name='expenses_bu_user_id_89990b_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['category'], name='expenses_bu_categor_30e867_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['month'], name='expenses_bu_month_7ca37b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user'], name='expenses_ex_user_id_51d8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['next_run_date'], name='expenses_re_next_ru_338658_idx'),
        ),
    ]
