# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_recurringexpense_and_expense_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
        migrations.RunSQL(
            sql="UPDATE expenses_expense SET description = note WHERE description = '' OR description IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
